DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS(ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(255) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(255) NOT NULL,
PROVINCIA VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES(ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL,
APELLIDO VARCHAR(255) NOT NULL,
DNI INT,
FECHA_INGRESO DATE,
DOMICILIO_ID INT);